let DATA=[], filtered=[], meaningQ=null, practiceQ=null, meaningScore=[0,0], practiceScore=[0,0];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fields=[['past','ماضٍ'],['present','مضارع'],['amr','أمر'],['active','اسم فاعل'],['passive','اسم مفعول'],['masdar','مصدر']];
const stripHarakat=s=>(s||'').normalize('NFKC').replace(/[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED]/g,'');
function match(hay,needle){return ($('#ignoreHarakat').checked?stripHarakat(hay):hay).toLocaleLowerCase().includes(($('#ignoreHarakat').checked?stripHarakat(needle):needle).toLocaleLowerCase())}
function card(x){return `<article class="verb" data-n="${x.sourceNumber}"><div class="verbtop"><span>#${x.sourceNumber} • ${x.symbol}</span><span>${x.occurrenceCount}×</span></div><div class="arabic">${x.forms.past.finalForm||x.forms.past.source}</div><div class="root">${x.root}</div><div class="meaning">${x.meaning||'—'}</div><div class="mini">${x.rootType} • page ${x.sourcePage}</div></article>`}
function render(){let q=$('#search').value.trim(), form=$('#form').value; filtered=DATA.filter(x=>(!form||x.symbol===form)&&(!q||match(String(x.sourceNumber),q)||match(x.root,q)||match(x.meaning||'',q)||fields.some(([k])=>match(x.forms[k].finalForm||'',q)))); $('#resultInfo').textContent=`${filtered.length} result${filtered.length===1?'':'s'}`; $('#list').innerHTML=filtered.slice(0,300).map(card).join(''); $$('#list .verb').forEach(e=>e.onclick=()=>openDetail(+e.dataset.n));}
function openDetail(n){let x=DATA[n-1]; if(!x)return; let rows=fields.map(([k,l])=>`<div class="label">${l}</div><div class="ar">${x.forms[k].finalForm||'—'}${x.forms[k].complement?` <span class="mini">${x.forms[k].complement}</span>`:''}</div>`).join(''); $('#detail').innerHTML=`<div class="verbtop">#${x.sourceNumber} • ${x.symbol} • ${x.occurrenceCount}×</div><div class="arabic">${x.forms.past.finalForm||''}</div><div class="root">الجذر: ${x.root}</div><p><b>${x.meaning||'—'}</b></p><div class="forms">${rows}</div><p class="mini">Source example: <span dir="rtl">${x.example?.source||'—'}</span></p>`; $('#modal').classList.remove('hidden')}
function randomOther(x){let y; do{y=DATA[Math.floor(Math.random()*DATA.length)]}while(y.sourceNumber===x.sourceNumber);return y}
function newMeaning(){let x=DATA[Math.floor(Math.random()*DATA.length)], opts=[x,randomOther(x),randomOther(x),randomOther(x)]; opts=[...new Map(opts.map(o=>[o.sourceNumber,o])).values()].sort(()=>Math.random()-.5); meaningQ=x; $('#meaningPrompt').innerHTML=`<div class="prompt"><div class="big">${x.forms.past.finalForm}</div><div class="mini">${x.root} • ${x.symbol}</div></div>`; $('#meaningChoices').innerHTML=opts.map(o=>`<button class="choice" data-n="${o.sourceNumber}">${o.meaning||'—'}</button>`).join(''); $$('#meaningChoices .choice').forEach(b=>b.onclick=()=>answerMeaning(b,+b.dataset.n));}
function answerMeaning(btn,n){let ok=n===meaningQ.sourceNumber; $$('#meaningChoices .choice').forEach(b=>{b.disabled=true;if(+b.dataset.n===meaningQ.sourceNumber)b.classList.add('correct')});if(!ok)btn.classList.add('wrong');meaningScore[1]++;if(ok)meaningScore[0]++;$('#meaningScore').textContent=`${meaningScore[0]} / ${meaningScore[1]}`}
function newPractice(){let x=DATA[Math.floor(Math.random()*DATA.length)], [k,l]=fields[Math.floor(Math.random()*fields.length)], ans=x.forms[k].finalForm; if(!ans){return newPractice()} let others=[];while(others.length<3){let y=randomOther(x),a=y.forms[k].finalForm;if(a&&!others.includes(a)&&a!==ans)others.push(a)} let opts=[ans,...others].sort(()=>Math.random()-.5);practiceQ={x,k,ans};$('#practicePrompt').innerHTML=`<div class="prompt"><div class="mini">${l} for:</div><div class="big">${x.forms.past.finalForm}</div><div class="mini">root: ${x.root} • ${x.symbol}</div></div>`;$('#practiceChoices').innerHTML=opts.map(o=>`<button class="choice" data-a="${o}">${o}</button>`).join('');$$('#practiceChoices .choice').forEach(b=>b.onclick=()=>answerPractice(b,b.dataset.a));}
function answerPractice(btn,a){let ok=a===practiceQ.ans;$$('#practiceChoices .choice').forEach(b=>{b.disabled=true;if(b.dataset.a===practiceQ.ans)b.classList.add('correct')});if(!ok)btn.classList.add('wrong');practiceScore[1]++;if(ok)practiceScore[0]++;$('#practiceScore').textContent=`${practiceScore[0]} / ${practiceScore[1]}`}
function switchTab(mode){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));['browse','meaning','practice'].forEach(id=>$('#'+id).classList.toggle('hidden',id!==mode));if(mode==='meaning')newMeaning();if(mode==='practice')newPractice()}
$('#search').oninput=render;$('#form').onchange=render;$('#ignoreHarakat').onchange=render;$('#close').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};$$('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.mode));$('#nextMeaning').onclick=newMeaning;$('#nextPractice').onclick=newPractice;
fetch('data/verbs.json').then(r=>r.json()).then(obj=>{DATA=obj.verbs;$('#count').textContent=DATA.length;render()});
